name: Tag and Release Go Library

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Ensure dependencies are in sync
      - name: Install dependencies
        run: go mod tidy

      # Generate semantic version tag based on commit messages
      - name: Bump version and create tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "v"

      # Push new tag to the repository
      - name: Push tags
        run: |
          git push origin ${{ steps.tag_version.outputs.new_tag }}

      # Create a release
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            This release includes the following changes:
            ${{ github.event.before }}..${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}